config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'
  resources :chows
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chow.rb
class Chow < ApplicationRecord
	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	 validates :email, presence: true, length: { maximum: 255 },

                    format: { with: VALID_EMAIL_REGEX },

                    uniqueness: { case_sensitive: false }

     validates :street_address, presence: true, length: { maximum: 255 }
     validates :city, presence: true, length: { maximum: 50 }
     validates :state, presence: true, length: { maximum: 2 }
     validates :zipcode, presence: true, numericality: {other_than: 0}
     validates :pooch_name, presence: true, length: { maximum: 50 }
     validates :age, presence: true, numericality: {other_than: 0}
     validates :birthday, presence: true 
     validates :special_needs, presence: true, length: { maximum: 350 }

    has_secure_password

    def Chow.digest(string)

    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :

                                                  BCrypt::Engine.cost

    BCrypt::Password.create(string, cost: cost)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/chows_controller.rb
class ChowsController < ApplicationController
	def index
		@chowers = Chow.all
	end

	def create
		@chow = Chow.new(chow_params)
		if @chow.save
			log_in @chow
			redirect_to @chow
		else
			#try again
		end
	end

	def show
		@chow = Chow.find(params[:id])
	end

	def edit
		@chow = Chow.find(params[:id])
	end

	def update
		@chow = Chow.find(params[:id])
		if @chow.update(chow_params)
			redirect_to @chow
		else
			#unable to update please try again
			render 'edit'
		end
	end

	def destroy
		@chow = Chow.find(params[:id])
		@chow.destroy
		redirect_to root_url
	end

	private
	def chow_params
		params.require(:chow).permit(:email, :password, :password_confirmation, :street_address, :city, :state, :zipcode, :pooch_name, :age, :birthday, :special_needs)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = Chow.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])

      log_in user

      redirect_to user

    else

      flash.now[:danger] = 'Invalid email/password combination'

      render 'new'

    end
end

    def destroy
    	log_out
    	redirect_to root_url
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title (page_title = '')
		base_title = "W'roof" 
		if page_title.empty?
			base_title
		else 
			page_title + " - " + base_title
		end
	end
end

app/helpers/chows_helper.rb
module ChowsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end


	def current_user
		@current_user ||= Chow.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/views/chows/_edit.html.erb
<%= form_for :chow, url: chow_path do |f| %>
<div class="parent-form">
	<h4 style="text-align: center; font-family: 'Maven Pro', sans-serif;"> COLLECT A FEW BOWLS </h4>
<label>
<%= f.email_field :email,:required => true %> 
<div class="label-text" > Email </div>
</label>

<label>
<%= f.password_field :password, :required => true %>
<div class="label-text" > Password </div>
</label>

<label>
<%= f.password_field :password_confirmation, :required => true %>
<div class="label-text" > Password Confirmation </div>
</label>

<label>
<%= f.text_field :street_address, :required => true %>
<div class="label-text" > Street Address </div>
</label>

<label>
<%= f.text_field :city, :required => true %>
<div class="label-text" > City </div>
</label>

<label>
<%= f.select :state, [ 'AK', 'AL', 'AR','AZ', 'CA','CO','CT','DE','FL','GA','HI','IA','ID','IL','IN','KS','KY','LA','MA','MD','ME','MI','MN','MO','MS','MT','NC','ND','NE','NH','NJ','NM','NV','NY','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VA','VT','WA','WI','WV','WY'] %>
<div class="label-text" > State </div>
</label>

<label>
<%= f.number_field :zipcode, :required => true, :min => 00000 %>
<div class="label-text" > Zipcode </div>
</label>

</div>

<div class="pooch-form">

<label>
<%= f.text_field :pooch_name, :required => true %>
<div class="label-text" > Pooch Name </div>
</label>

<label>
<%= f.number_field :age, :required => true, :min => 0, :max => 25 %>
<div class="label-text" > Age </div>
</label>


<label>
<%= f.date_field :birthday, :required => true %>
<div class="label-text" > Birthday </div>
</label>

<label>
<%= f.text_area :special_needs, :required => true, :cols => 45, :rows => 4 %>
<div class="label-text" >  </div>
</label>

</div>
<%= f.submit "Update" , :id => "chow-collect"%>
<% end %>

app/views/chows/_signup.html.erb
<%= form_for :chow, url: chows_path do |f| %>
<div class="parent-form">
	<h4 style="text-align: center; font-family: 'Maven Pro', sans-serif;"> COLLECT A FEW BOWLS </h4>
<label>
<%= f.email_field :email,:required => true %> 
<div class="label-text" > Email </div>
</label>

<label>
<%= f.password_field :password, :required => true %>
<div class="label-text" > Password </div>
</label>

<label>
<%= f.password_field :password_confirmation, :required => true %>
<div class="label-text" > Password Confirmation </div>
</label>

<label>
<%= f.text_field :street_address, :required => true %>
<div class="label-text" > Street Address </div>
</label>

<label>
<%= f.text_field :city, :required => true %>
<div class="label-text" > City </div>
</label>

<label>
<%= f.select :state, [ 'AK', 'AL', 'AR','AZ', 'CA','CO','CT','DE','FL','GA','HI','IA','ID','IL','IN','KS','KY','LA','MA','MD','ME','MI','MN','MO','MS','MT','NC','ND','NE','NH','NJ','NM','NV','NY','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VA','VT','WA','WI','WV','WY'] %>
<div class="label-text" > State </div>
</label>

<label>
<%= f.number_field :zipcode, :required => true, :min => 00000 %>
<div class="label-text" > Zipcode </div>
</label>

</div>

<div class="pooch-form">

<label>
<%= f.text_field :pooch_name, :required => true %>
<div class="label-text" > Pooch Name </div>
</label>

<label>
<%= f.number_field :age, :required => true, :min => 0, :max => 25 %>
<div class="label-text" > Age </div>
</label>


<label>
<%= f.date_field :birthday, :required => true %>
<div class="label-text" > Birthday </div>
</label>

<label>
<%= f.text_area :special_needs, :required => true, :cols => 45, :rows => 4 %>
<div class="label-text" >  </div>
</label>

</div>
<%= f.submit "Collect A Few Bowls" , :id => "chow-collect"%>
<% end %>

app/views/chows/show.html.erb
<% provide(:title, "Dashboard") %>
<div id="chow-dash">
	<h4 style="font-size: 2.5em;  position: fixed;left: 5px; top: 2px;"> Hello, <%= @chow.pooch_name %></h4>
	<%=  image_tag("wroof-01.png", alt: "login",  :class => "main-imgs", :id => 'chow-dash-Icon') %>

	<div id="chow-opts">
		<p class="chow-bttns" id="days-chow"> days left </p>
		<p class="chow-bttns" id="edit-chow"> edit account </p>
		<p class="chow-bttns" id="close-chow"> close account </p>
	</div>

	<div class="chow-main" id="chow-countdown">
		<h4 style="color: #E97726;"> DAYS LEFT TILL NEXT DROP OFF</h4>
		<div id="days-to-chow">
			<p style="font-size: 7.5em; color: white; padding-top: 0px; position: fixed;left: 48%; top: 18%;"> 25 </p>
		</div>
	</div>

	<div class="chow-main"id="edit-acct">
		<%= render 'chows/edit' %>
	</div>


	<hr style="position:fixed; top: 65%; left: 20%;">

	<div id="chow-updates">
		<h4 id="chow-dash-header" style="position:fixed; top: 70%; left: 45%;"> Messages </h4>
		<p style="position:fixed; top: 75%; left: 45%;"> Messages and Notifications go here </p>
	</div>

	<%= link_to "LogOut", logout_path, :id => "logout", method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Caveat|Gloria+Hallelujah|Indie+Flower|Maven+Pro&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<div id="home-page">
	<%=link_to  image_tag("wroof-01.png", alt: "login",  :class => "main-imgs", :id => 'rootIcon') , root_url%>
	<div id="icons">
	<h1 id="name-icon"> W'roof </h1>
	<h4 id="sub-icon"> Bowl </h4>
	<%=  image_tag("bowl-01.png", alt: "login",  :class => "main-imgs", :id => 'bowlIcon') %>
	<p id="sub-header"> - we keep the pooches fed - </p> 
</div>

	<div id="app-info">

		<div class="home-intro" id="about">
			<h4 class="home-headers"> ABOUT US </h4>
			<hr>
			<p> We love dogs. We love making sure that
				every dog is happy and playful. We believe that 
				a happy and playful dog is first and foremost a 
				well-fed dog. So we take it upon ourselves to 
				ensure that all pooches are well-fed and cared for
				at all times by offering giftcards for petfood and
				immediate needs. That pooch could be my pooch's friend.</p>
		</div>

		<div class="home-intro" id="howItWorks">
			<h4 class="home-headers"> HOW IT WORKS </h4>
			<hr>
			<p> We raise funds to buy giftcards to petstores and
				offer these cards to pooches who need the some 
				help. Offering a giftcard every month allows the
				pooches to have the food they need and a few other 
				essential items to get them through the month. We also
				offer grooming and vaccination funds when we can in raffle
				draws. </p>
		</div>


		<div class="home-intro" id="feed">
			<h4 class="home-headers"> BE A FRIEND </h4>
			<hr>
			<p> Please click the button below and give to become part of something wonderful. We all love to take care of our pets, lets help care for their friends in need.</p>

			<button id="baf"> BE A FRIEND </button>
		</div>

		<div class="home-intro" id="request">
			<h4 class="home-headers"> REQUEST </h4>
			<hr>
			<p> Every pooch deserves love. Your pooch is the friend my pooch hasn't met yet. Enter your address so we can send you the giftcard to care for your pooch. </p>

			<button id="chowbttn"> COLLECT CHOW</button>
		</div>

	</div>
</div>

<div class="home-opts" id="friend">
	<h1 style="text-align: center; font-family: 'Maven Pro', sans-serif;"> GIVE HERE </h1>
	<a id="friends" href="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=thelovelypractice%40gmail.com&item_name=Ensure+pooches+are+well-fed&currency_code=USD&source=url"> <%=  image_tag("wroof-01.png", alt: "login",  :class => "main-imgs", :id => 'wroofIcon') %> <p id="give-home">CLICK THE PAW TO GIVE <p></a>
</div>

<div class="home-opts" id="chow">
	<%= render 'chows/signup'%>
</div>


<div class="home-opts" id="chow-login">
	<%= render 'sessions/login'%>
</div>